Microverse first project
hislordshipprof/Hello-Microverse pull request #1
Opened 2022-05-24 15:44 UTC by hislordshipprof

In this project ;
Created an Html template
Created Css style sheet
Committed each of the files created individually
Created a test,md file and added it to gitignore

2022-05-24 16:03 UTC, phelian23 requested changes
Hi @hislordshipprof, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct use of Github Flow
✅ Good commit messages
✅ Descriptive PR

## Required Changes ♻️
- [ ] The linters file is not set up correctly. Kindly follow the instructions [here](https://github.com/microverseinc/linters-config) to set up the linters correctly.
- [ ] Please use [this template](https://github.com/microverseinc/readme-template) to make you README.md file descriptive, but remember to customize it to your project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 12:01 UTC, aimemalaika approved these changes
Hi @hislordshipprof, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 16:34 UTC, Mre55 requested changes
**Hi @hislordshipprof,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 16:34 UTC, Mre55 commented on index.html
> +          </section>
Kindly, stick to the design provided as much as possible. This section has a background image please add the image as background inside your CSS file. And also it has a border-radius at the left top of the section. Match the text font-weight as the design.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="364" alt="image" src="https://user-images.githubusercontent.com/34578631/171453230-46117cc6-27a4-4632-8ba5-b657752580ac.png"> | <img width="363" alt="image" src="https://user-images.githubusercontent.com/34578631/171453479-070626bc-0fb1-4da6-a444-cd07e3c47277.png"> |

2022-06-01 16:34 UTC, Mre55 commented on index.html
> +                    </button>
Please match the design for your `Get In Touch` button` it should be somewhere in the middle between the text area filed and the bottom end. Currently, it's more to the bottom kindly edit its position and the button text spacing and alignment.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="363" alt="image" src="https://user-images.githubusercontent.com/34578631/171454369-f937e04a-4a5e-4450-9f9e-8b7b8d633549.png"> | <img width="363" alt="image" src="https://user-images.githubusercontent.com/34578631/171454436-a905d54b-6b3d-4f42-8467-7731a95ebe4a.png"> |

2022-06-01 23:35 UTC, rotimiazeez approved these changes
# Hi @hislordshipprof :wave, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 08:48 UTC, merged